services:
  datasource:
    container_name: datasource
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: test
